config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :new, :create, :show] do
    resources :reviews, only: [:index, :new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true
  validates :category, inclusion: { in: %w(chinese italian japanese french belgian) }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true

  validates_numericality_of :rating
  validates :rating, inclusion: 0..5

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def new
    @restaurant = Restaurant.new
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @restaurant = Restaurant.find(params[:restaurant_id])
    @reviews = @restaurant.reviews
  end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new

  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = Restaurant.find(params[:restaurant_id])
    @restaurant = Restaurant.find(params[:restaurant_id])
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<div>
  <% @restaurants.each do |restaurant|  %>
    <p> <%= link_to restaurant.name, restaurant_path(restaurant) %> </p>
  <% end %>
</div>

<div>
  <%= link_to 'Create new restaurant', new_restaurant_path %>
</div>

app/views/restaurants/new.html.erb
<div>Create new restaurant</div>

  <% @categories = %w(chinese italian japanese french belgian) %>

<div>
  <%= simple_form_for (@restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, collection: @categories %>

  <%= f.submit "Create restaurant", class: "btn btn-primary" %>
<% end %>
</div>

app/views/restaurants/show.html.erb
<div>
  <ul>
    <li> <%= @restaurant.name %> </li>
    <li> <%= @restaurant.address %> </li>
    <li> <%= @restaurant.phone_number %> </li>
    <li> <%= @restaurant.category %> </li>

  </ul>
</div>

<div>
    <%= link_to 'See reviews!', restaurant_reviews_path(@restaurant) %>
 </div>

 <div>
    <%= link_to 'Add review!', new_restaurant_review_path(@restaurant) %>
 </div>

app/views/reviews/index.html.erb
<div>check connection</div>

<p>
<% @reviews.each do |review| %>
  <p> <%= "Rating: #{review.rating}, Content: #{review.content}" %> </p>
<% end %>
</p>

app/views/reviews/new.html.erb
<div>Create new review</div>

<div>
  <%= simple_form_for [ @restaurant, @review ] do |f| %>
  <%= f.input :rating %>
  <%= f.input :content %>

  <%= f.submit "Add review", class: "btn btn-primary" %>
<% end %>
</div>